/**
 * Prompt 3: Schema → Entity Instantiation
 * 
 * This prompt is used to generate canonical names and aliases for entities.
 * It is used in 50% of entity instantiations (random sampling) to balance
 * accuracy and token consumption.
 * 
 * Design Reference: Phase 2 - Prompt Module, Section 5 - Entity Builder (Enhanced with LLM)
 * Requirements: 4.3, 4.4, 11.5
 */

/**
 * Build entity name standardization prompt for LLM
 * 
 * This prompt should be used when:
 * 1. Random sampling (50% probability) for quality improvement
 * 2. Entity name is not well-formed (contains special chars, inconsistent format)
 * 3. Entity name needs disambiguation (multiple possible interpretations)
 * 
 * @param {string} rawName - Raw entity name generated by rules
 * @param {string} entityType - Type of entity (EventEntity, LocationEntity, etc.)
 * @param {Object} context - Additional context
 * @param {string} context.text - Original text from CKB
 * @param {Array} context.fields - Extracted fields
 * @param {Object} context.schema - Schema that triggered entity creation
 * @param {Object} options - Additional options
 * @param {boolean} options.includeExamples - Whether to include examples
 * @param {number} options.maxAliases - Maximum number of aliases to generate (default: 3)
 * @returns {string} Complete prompt for LLM
 */
function buildEntityNamePrompt(rawName, entityType, context = {}, options = {}) {
  const {
    includeExamples = true,
    maxAliases = 3
  } = options;

  // Build context section
  const contextSection = buildContextSection(context);
  
  // Build entity type guidance
  const entityTypeSection = buildEntityTypeSection(entityType);
  
  // Build examples section
  const examplesSection = includeExamples ? buildExamplesSection() : '';
  
  // Build constraints section
  const constraintsSection = buildConstraintsSection();

  return `你是一个知识图谱实体标准化专家。你的任务是为实体生成规范的名称和常见别名。

## 原始实体名称
${rawName}

## 实体类型
${entityType}

${contextSection}

${entityTypeSection}

## 任务要求
1. 生成一个规范的实体名称（canonical_name）
2. 生成 2-${maxAliases} 个常见别名（aliases）
3. 规范名称应该：
   - 去除冗余词汇（如"的"、"了"等）
   - 统一格式（如"阿里C区" vs "阿里 C 区"）
   - 保持简洁明确
   - 符合该实体类型的命名规范
4. 别名应该包括：
   - 常见的简称或缩写
   - 不同的表述方式
   - 可能的同义词
5. **只基于原始文本和已提取字段，不要推理或创造新信息**

${examplesSection}

${constraintsSection}

## 输出格式
请严格按照以下 JSON 格式输出，不要包含其他文字：

{
  "canonical_name": "规范的实体名称",
  "aliases": ["别名1", "别名2", "别名3"],
  "reasoning": "简短说明标准化的理由"
}`;
}

/**
 * Build context section
 * @param {Object} context - Context information
 * @returns {string} Formatted section
 */
function buildContextSection(context) {
  if (!context || (!context.text && !context.fields)) {
    return '';
  }
  
  let section = '';
  
  if (context.text) {
    section += `## 原始文本\n${context.text}\n\n`;
  }
  
  if (context.fields && context.fields.length > 0) {
    const fieldsList = context.fields
      .map(f => `- ${f.name}: ${f.value} (${f.type})`)
      .join('\n');
    section += `## 提取的字段\n${fieldsList}\n\n`;
  }
  
  if (context.schema) {
    section += `## 触发的 Schema\n${context.schema.schema_name}\n\n`;
  }
  
  return section;
}

/**
 * Build entity type guidance section
 * @param {string} entityType - Type of entity
 * @returns {string} Formatted section
 */
function buildEntityTypeSection(entityType) {
  const typeGuidance = {
    'EventEntity': {
      description: '事件实体：描述发生的事件或变化',
      naming_rules: [
        '格式：区域_指标_时间 或 主体_动作_时间',
        '示例：阿里C区_水位下降_2025-01',
        '保持简洁，去除"事件"、"发生"等冗余词'
      ],
      alias_types: [
        '简化版本（去掉时间）',
        '口语化表述',
        '关键词组合'
      ]
    },
    'LocationEntity': {
      description: '地点实体：描述地理位置或区域',
      naming_rules: [
        '使用标准地名',
        '统一格式（去除多余空格）',
        '保留行政级别（如"市"、"区"、"县"）'
      ],
      alias_types: [
        '简称（如"北京"代替"北京市"）',
        '全称（如"北京市"代替"北京"）',
        '其他常见称呼'
      ]
    },
    'PersonEntity': {
      description: '人物实体：描述个人',
      naming_rules: [
        '使用全名',
        '去除称谓（如"先生"、"女士"）',
        '统一格式'
      ],
      alias_types: [
        '常见昵称',
        '职位称呼',
        '其他称谓'
      ]
    },
    'OrganizationEntity': {
      description: '组织实体：描述公司、机构、团体',
      naming_rules: [
        '使用官方全称',
        '去除"有限公司"、"股份有限公司"等后缀（可选）',
        '统一格式'
      ],
      alias_types: [
        '简称或缩写',
        '英文名称',
        '常见俗称'
      ]
    },
    'IndicatorEntity': {
      description: '指标实体：描述度量指标或属性',
      naming_rules: [
        '使用标准术语',
        '统一单位表示',
        '去除冗余修饰词'
      ],
      alias_types: [
        '同义词',
        '不同表述方式',
        '相关术语'
      ]
    }
  };

  const guidance = typeGuidance[entityType] || {
    description: '通用实体',
    naming_rules: ['使用简洁明确的名称', '去除冗余词汇', '统一格式'],
    alias_types: ['常见别名', '同义词', '其他表述']
  };

  const rulesStr = guidance.naming_rules.map(r => `  - ${r}`).join('\n');
  const aliasTypesStr = guidance.alias_types.map(t => `  - ${t}`).join('\n');

  return `## 实体类型说明
**${entityType}**: ${guidance.description}

**命名规范**:
${rulesStr}

**别名类型**:
${aliasTypesStr}`;
}

/**
 * Build examples section
 * @returns {string} Formatted section with examples
 */
function buildExamplesSection() {
  return `## 标准化示例

**示例 1：事件实体**

原始名称：阿里C区_水位_2025-01
实体类型：EventEntity
原始文本：阿里C区2025年1月水位下降10米

输出：
{
  "canonical_name": "阿里C区水位下降_2025-01",
  "aliases": ["阿里C区水位变化", "阿里C区2025年1月水位事件", "C区水位下降"],
  "reasoning": "规范化为'区域+指标+变化+时间'格式，去除冗余词汇，生成简化和口语化别名"
}

**示例 2：地点实体**

原始名称：阿里 C 区
实体类型：LocationEntity
原始文本：阿里 C 区的水位监测数据

输出：
{
  "canonical_name": "阿里C区",
  "aliases": ["阿里C", "C区", "阿里监测区C"],
  "reasoning": "统一格式，去除多余空格，生成常见简称"
}

**示例 3：人物实体**

原始名称：张三先生
实体类型：PersonEntity
原始文本：张三先生在阿里巴巴担任工程师

输出：
{
  "canonical_name": "张三",
  "aliases": ["张工", "小张", "张三工程师"],
  "reasoning": "去除称谓'先生'，生成职位称呼和常见昵称"
}

**示例 4：组织实体**

原始名称：阿里巴巴集团控股有限公司
实体类型：OrganizationEntity
原始文本：阿里巴巴集团控股有限公司发布财报

输出：
{
  "canonical_name": "阿里巴巴",
  "aliases": ["阿里", "Alibaba", "阿里集团"],
  "reasoning": "简化为常用名称，保留核心品牌名，添加英文名和常见简称"
}

**示例 5：指标实体**

原始名称：地下水位高度
实体类型：IndicatorEntity
原始文本：监测地下水位高度的变化

输出：
{
  "canonical_name": "水位",
  "aliases": ["地下水位", "水位高度", "水面高度"],
  "reasoning": "简化为核心术语'水位'，保留完整表述和同义词作为别名"
}

**示例 6：已经规范的名称**

原始名称：北京市
实体类型：LocationEntity
原始文本：北京市2024年GDP增长5.2%

输出：
{
  "canonical_name": "北京市",
  "aliases": ["北京", "首都", "京"],
  "reasoning": "原始名称已经规范，保持不变，添加常见简称和别称"
}`;
}

/**
 * Build constraints section
 * @returns {string} Formatted section with constraints
 */
function buildConstraintsSection() {
  return `## 重要约束

1. **基于原文**：只基于原始文本和已提取字段进行标准化，不要创造新信息
   - ❌ 错误：原文说"水位下降"，不要推理出"可能导致干旱"并添加到名称中
   - ✅ 正确：只标准化"水位下降"这个事实

2. **保持语义**：规范名称必须保持原始名称的核心语义
   - ❌ 错误：将"水位下降"改为"水位变化"（改变了方向性）
   - ✅ 正确：将"水位下降了"改为"水位下降"（去除冗余词）

3. **别名质量**：
   - 别名必须是该实体的真实别称，不是相关实体
   - 别名应该是常见的、自然的表述
   - 避免生成过于相似的别名（如"阿里C区"和"阿里 C 区"）
   - 如果实在找不到合适的别名，可以少于最大数量

4. **格式统一**：
   - 去除多余空格（"阿里 C 区" → "阿里C区"）
   - 去除冗余标点（"水位下降！" → "水位下降"）
   - 统一日期格式（"2025年1月" → "2025-01"）
   - 去除冗余词汇（"的"、"了"、"事件"等）

5. **实体类型一致性**：
   - 规范名称和别名必须符合实体类型的命名规范
   - 不要混淆不同类型的实体（如将事件名称用于地点实体）

6. **简洁性**：
   - 规范名称应该简洁明确，通常不超过 20 个字符
   - 避免过长的描述性名称
   - 如果原始名称已经很简洁，可以保持不变

7. **推理说明**：
   - reasoning 字段应简短（1-2句话）
   - 说明主要的标准化操作（去除了什么、统一了什么、为什么这样命名）
   - 对于已经规范的名称，说明"原始名称已规范"`;
}

/**
 * Build a simplified prompt for quick entity naming (fewer tokens)
 * 
 * @param {string} rawName - Raw entity name
 * @param {string} entityType - Entity type
 * @param {Object} context - Additional context
 * @returns {string} Simplified prompt
 */
function buildSimplifiedPrompt(rawName, entityType, context = {}) {
  const textContext = context.text ? `\n文本：${context.text}` : '';
  
  return `标准化实体名称并生成2-3个别名。只基于原文，不推理。${textContext}

原始名称：${rawName}
类型：${entityType}

输出JSON：
{
  "canonical_name": "规范名称",
  "aliases": ["别名1", "别名2", "别名3"],
  "reasoning": "理由"
}

要求：
- 去除冗余词汇和多余空格
- 统一格式
- 别名应是常见表述
- 保持核心语义不变`;
}

/**
 * Build entity disambiguation prompt for LLM
 * 
 * This prompt is used to determine if two entities are the same entity
 * with different names (30% probability sampling for cost control).
 * 
 * @param {Object} entity1 - First entity
 * @param {string} entity1.canonical_name - Canonical name
 * @param {Array} entity1.aliases - Aliases
 * @param {Object} entity1.attributes - Attributes
 * @param {Object} entity2 - Second entity (same structure as entity1)
 * @param {Object} options - Additional options
 * @param {boolean} options.includeExamples - Whether to include examples
 * @returns {string} Complete prompt for LLM
 */
function buildEntityDisambiguationPrompt(entity1, entity2, options = {}) {
  const {
    includeExamples = true
  } = options;

  // Build entity comparison section
  const comparisonSection = buildEntityComparisonSection(entity1, entity2);
  
  // Build examples section
  const examplesSection = includeExamples ? buildDisambiguationExamplesSection() : '';
  
  // Build constraints section
  const disambiguationConstraints = buildDisambiguationConstraintsSection();

  return `你是一个知识图谱实体消歧专家。你的任务是判断两个实体是否为同一实体。

${comparisonSection}

## 任务要求
1. 判断这两个实体是否为同一实体
2. 提供置信度评分（0-1）
3. 说明判断理由
4. 如果是同一实体，建议使用哪个名称作为规范名称

${examplesSection}

${disambiguationConstraints}

## 输出格式
请严格按照以下 JSON 格式输出，不要包含其他文字：

{
  "is_same": true,
  "confidence": 0.95,
  "reasoning": "判断理由",
  "recommended_canonical_name": "建议的规范名称"
}`;
}

/**
 * Build entity comparison section
 * @param {Object} entity1 - First entity
 * @param {Object} entity2 - Second entity
 * @returns {string} Formatted section
 */
function buildEntityComparisonSection(entity1, entity2) {
  const formatEntity = (entity, label) => {
    const aliasesStr = entity.aliases && entity.aliases.length > 0
      ? entity.aliases.join('、')
      : '无';
    
    const attributesStr = entity.attributes && Object.keys(entity.attributes).length > 0
      ? Object.entries(entity.attributes)
          .map(([key, value]) => `  - ${key}: ${value}`)
          .join('\n')
      : '  无';

    return `### ${label}
- **规范名称**: ${entity.canonical_name}
- **别名**: ${aliasesStr}
- **属性**:
${attributesStr}`;
  };

  return `## 实体对比

${formatEntity(entity1, '实体1')}

${formatEntity(entity2, '实体2')}`;
}

/**
 * Build disambiguation examples section
 * @returns {string} Formatted section with examples
 */
function buildDisambiguationExamplesSection() {
  return `## 消歧示例

**示例 1：同一实体（名称变体）**

实体1：
- 规范名称：阿里巴巴
- 别名：阿里、Alibaba
- 属性：类型=公司、行业=互联网

实体2：
- 规范名称：阿里巴巴集团
- 别名：阿里集团、阿里
- 属性：类型=公司、行业=科技

输出：
{
  "is_same": true,
  "confidence": 0.95,
  "reasoning": "两个实体都指向阿里巴巴公司，别名重叠（'阿里'），属性相似（都是公司，行业相关），只是名称表述略有不同",
  "recommended_canonical_name": "阿里巴巴"
}

**示例 2：不同实体（名称相似）**

实体1：
- 规范名称：北京市
- 别名：北京、首都
- 属性：类型=城市、级别=直辖市

实体2：
- 规范名称：北京大学
- 别名：北大、PKU
- 属性：类型=大学、位置=北京

输出：
{
  "is_same": false,
  "confidence": 0.98,
  "reasoning": "虽然都包含'北京'，但实体类型完全不同（城市 vs 大学），属性无重叠，是两个不同的实体",
  "recommended_canonical_name": null
}

**示例 3：同一实体（简称和全称）**

实体1：
- 规范名称：GDP
- 别名：国内生产总值、经济总量
- 属性：类型=经济指标、单位=元

实体2：
- 规范名称：国内生产总值
- 别名：GDP、经济产出
- 属性：类型=经济指标、单位=元

输出：
{
  "is_same": true,
  "confidence": 0.99,
  "reasoning": "两个实体互为别名（GDP ↔ 国内生产总值），属性完全一致，明显是同一指标的不同表述",
  "recommended_canonical_name": "GDP"
}

**示例 4：不确定（需要更多信息）**

实体1：
- 规范名称：张三
- 别名：小张
- 属性：职位=工程师

实体2：
- 规范名称：张三
- 别名：张工
- 属性：职位=经理

输出：
{
  "is_same": false,
  "confidence": 0.6,
  "reasoning": "名称相同但属性冲突（工程师 vs 经理），可能是同名不同人，也可能是同一人晋升，置信度较低，建议保留为两个实体",
  "recommended_canonical_name": null
}`;
}

/**
 * Build disambiguation constraints section
 * @returns {string} Formatted section with constraints
 */
function buildDisambiguationConstraintsSection() {
  return `## 判断标准

1. **名称匹配**：
   - 规范名称完全相同 → 很可能是同一实体
   - 规范名称包含关系（如"阿里巴巴" vs "阿里巴巴集团"）→ 可能是同一实体
   - 别名重叠 → 增加同一实体的可能性
   - 名称完全不同且无别名重叠 → 很可能是不同实体

2. **属性匹配**：
   - 属性完全一致 → 增加同一实体的可能性
   - 属性互补（无冲突）→ 可能是同一实体的不同描述
   - 属性冲突 → 降低同一实体的可能性
   - 核心属性冲突（如类型、身份）→ 很可能是不同实体

3. **置信度评估**：
   - 0.9-1.0：非常确定是/不是同一实体
   - 0.7-0.9：比较确定
   - 0.5-0.7：不太确定，建议保留为两个实体
   - < 0.5：完全不确定，必须保留为两个实体

4. **推荐规范名称**：
   - 如果 is_same=true，选择更简洁、更常用的名称
   - 如果 is_same=false，返回 null
   - 优先选择已有别名更多的实体的名称（说明更常用）

5. **保守原则**：
   - 当不确定时（confidence < 0.8），倾向于判断为不同实体
   - 宁可保留重复实体，也不要错误合并不同实体
   - 属性冲突时，必须判断为不同实体`;
}

/**
 * Validate entity naming result from LLM response
 * 
 * @param {Object} result - Result to validate
 * @param {string} rawName - Original raw name
 * @returns {Object} Validation result with valid data and errors
 */
function validateEntityNamingResult(result, rawName) {
  const errors = [];

  // Validate result structure
  if (!result || typeof result !== 'object') {
    errors.push('Result must be an object');
    return { validResult: null, errors };
  }

  // Validate canonical_name
  if (!result.canonical_name || typeof result.canonical_name !== 'string') {
    errors.push('canonical_name must be a non-empty string');
  } else if (result.canonical_name.trim().length === 0) {
    errors.push('canonical_name cannot be empty or whitespace');
  } else if (result.canonical_name.length > 100) {
    errors.push('canonical_name is too long (max 100 characters)');
  }

  // Validate aliases
  if (!Array.isArray(result.aliases)) {
    errors.push('aliases must be an array');
  } else {
    // Filter out empty aliases first for validation
    const nonEmptyAliases = result.aliases.filter(a => a && typeof a === 'string' && a.trim().length > 0);
    
    // Check for invalid aliases (non-string or empty after trim)
    const invalidAliases = result.aliases.filter(a => !a || typeof a !== 'string' || a.trim().length === 0);
    if (invalidAliases.length > 0 && nonEmptyAliases.length === 0) {
      // Only error if ALL aliases are invalid
      errors.push('All aliases are invalid (must be non-empty strings)');
    }
    
    // Check for duplicate aliases (only among non-empty ones)
    if (nonEmptyAliases.length > 0) {
      const uniqueAliases = new Set(nonEmptyAliases.map(a => a.trim()));
      if (uniqueAliases.size !== nonEmptyAliases.length) {
        errors.push('Aliases contain duplicates');
      }
      
      // Check if canonical_name is in aliases
      if (result.canonical_name && nonEmptyAliases.some(a => a.trim() === result.canonical_name.trim())) {
        errors.push('canonical_name should not be in aliases');
      }
    }
  }

  // Validate reasoning (optional but recommended)
  if (result.reasoning && typeof result.reasoning !== 'string') {
    errors.push('reasoning must be a string');
  }

  // If there are critical errors, return null
  if (errors.length > 0) {
    return { validResult: null, errors };
  }

  const validResult = {
    canonical_name: result.canonical_name.trim(),
    aliases: result.aliases.filter(a => a && a.trim().length > 0).map(a => a.trim()),
    reasoning: result.reasoning || ''
  };

  return { validResult, errors };
}

/**
 * Validate entity disambiguation result from LLM response
 * 
 * @param {Object} result - Result to validate
 * @returns {Object} Validation result with valid data and errors
 */
function validateDisambiguationResult(result) {
  const errors = [];

  // Validate result structure
  if (!result || typeof result !== 'object') {
    errors.push('Result must be an object');
    return { validResult: null, errors };
  }

  // Validate is_same
  if (typeof result.is_same !== 'boolean') {
    errors.push('is_same must be a boolean');
  }

  // Validate confidence
  if (typeof result.confidence !== 'number') {
    errors.push('confidence must be a number');
  } else if (result.confidence < 0 || result.confidence > 1) {
    errors.push(`confidence must be between 0 and 1, got ${result.confidence}`);
  }

  // Validate reasoning
  if (!result.reasoning || typeof result.reasoning !== 'string') {
    errors.push('reasoning must be a non-empty string');
  }

  // Validate recommended_canonical_name
  if (result.is_same === true) {
    if (!result.recommended_canonical_name || typeof result.recommended_canonical_name !== 'string') {
      errors.push('recommended_canonical_name must be provided when is_same=true');
    }
  } else if (result.is_same === false) {
    if (result.recommended_canonical_name !== null && result.recommended_canonical_name !== undefined) {
      errors.push('recommended_canonical_name should be null when is_same=false');
    }
  }

  // If there are critical errors, return null
  if (errors.length > 0) {
    return { validResult: null, errors };
  }

  const validResult = {
    is_same: result.is_same,
    confidence: result.confidence,
    reasoning: result.reasoning,
    recommended_canonical_name: result.is_same ? result.recommended_canonical_name : null
  };

  return { validResult, errors };
}

/**
 * Get prompt statistics (for token estimation)
 * 
 * @param {string} prompt - The prompt text
 * @returns {Object} Statistics about the prompt
 */
function getPromptStats(prompt) {
  const lines = prompt.split('\n').length;
  const chars = prompt.length;
  // Rough token estimation: ~4 chars per token for Chinese text
  const estimatedTokens = Math.ceil(chars / 4);

  return {
    lines,
    chars,
    estimatedTokens
  };
}

/**
 * Determine if entity name needs LLM standardization
 * 
 * @param {string} name - Entity name to check
 * @param {number} samplingRate - Random sampling rate (0-1), default 0.5
 * @returns {boolean} Whether to use LLM standardization
 */
function shouldUseLLMStandardization(name, samplingRate = 0.5) {
  // Always use LLM if name is not well-formed
  if (!isWellFormedName(name)) {
    return true;
  }
  
  // Random sampling for quality improvement
  return Math.random() < samplingRate;
}

/**
 * Check if entity name is well-formed
 * 
 * @param {string} name - Entity name to check
 * @returns {boolean} Whether the name is well-formed
 */
function isWellFormedName(name) {
  if (!name || typeof name !== 'string') {
    return false;
  }
  
  const trimmed = name.trim();
  
  // Check for empty or too short
  if (trimmed.length === 0 || trimmed.length < 2) {
    return false;
  }
  
  // Check for excessive whitespace
  if (/\s{2,}/.test(trimmed)) {
    return false;
  }
  
  // Check for special characters that indicate poor formatting
  if (/[!@#$%^&*()+=\[\]{};':"\\|,.<>?~`]/.test(trimmed)) {
    return false;
  }
  
  // Check for redundant words
  const redundantWords = ['的', '了', '事件', '情况', '现象'];
  if (redundantWords.some(word => trimmed.endsWith(word))) {
    return false;
  }
  
  return true;
}

module.exports = {
  buildEntityNamePrompt,
  buildSimplifiedPrompt,
  buildEntityDisambiguationPrompt,
  validateEntityNamingResult,
  validateDisambiguationResult,
  getPromptStats,
  shouldUseLLMStandardization,
  isWellFormedName
};
